ALTER TABLE SHT_PUSH_NOTIFY ADD (TMPCONTENT  CLOB);

UPDATE SHT_PUSH_NOTIFY SET TMPCONTENT=PUSH_CONTENT;

ALTER TABLE SHT_PUSH_NOTIFY DROP COLUMN PUSH_CONTENT;

ALTER TABLE SHT_PUSH_NOTIFY RENAME COLUMN TMPCONTENT TO PUSH_CONTENT;