CREATE TABLE "SHT_MSG_SMS" (
    SHT_MSG_SMS_ID           NUMBER(11)          NOT NULL,
    SHT_MSG_SMS_PHONE        NUMBER(11)          NOT NULL,
    SHT_MSG_SMS_CONTENT      VARCHAR2(500)       NOT NULL,
    SHT_MSG_SMS_STATUS       NUMBER(1)           DEFAULT 0 NOT NULL, -- 0 - Sending, 1 - Sent
    SHT_MSG_SMS_TYPE         NUMBER(2)           NOT NULL, -- 0 - Registration
    CMN_DELETE_FLAG          NUMBER(2)           DEFAULT 0 NOT NULL, -- 0 - False, 1 - True
    CMN_ENTRY_DATE           DATE                DEFAULT CURRENT_DATE NOT NULL,
    CMN_LAST_UPDT_DATE       DATE                DEFAULT CURRENT_DATE NOT NULL,
    CMN_ENTRY_USER_NO        NUMBER(11),
    CMN_ENTRY_USER_TYPE      NUMBER(1),
    CMN_LAST_UPDT_USER_NO    NUMBER(11),
    CMN_LAST_UPDT_USER_TYPE  NUMBER(1)
 );

ALTER TABLE "SHT_MSG_SMS"
ADD CONSTRAINT SHT_MSG_SMS_PK PRIMARY KEY (SHT_MSG_SMS_ID);

CREATE SEQUENCE SHT_MSG_SMS_SEQ START WITH 1;