ALTER TABLE
    "SHT_USER_NTF" DROP COLUMN "USER_NTF_STATUS";
ALTER TABLE
    "SHT_USER_NTF" DROP COLUMN "USER_NTF_TYPE";
ALTER TABLE
    "SHT_USER_NTF" DROP COLUMN "USER_NTF_CONT";
CREATE INDEX IDX_SHT_USER_NTF_IDX ON SHT_USER_NTF(USER_ID, USER_NTF_DEVICE_TOKEN);