CREATE TABLE
    SHT_USER_NTF
    (
        USER_NTF_ID NUMBER(11)  NOT NULL,
        USER_ID NUMBER(11)  NOT NULL,
        USER_NTF_DEVICE_TOKEN VARCHAR2(500) NOT NULL,
        USER_NTF_STATUS INTEGER DEFAULT 0 NOT NULL,
        USER_NTF_TYPE INTEGER DEFAULT 0 NOT NULL,
        USER_NTF_CONT VARCHAR2(1000),
        CMN_DELETE_FLAG NUMBER(1) DEFAULT 0 NOT NULL, -- 0 - False, 1 - True
        CMN_ENTRY_DATE DATE DEFAULT CURRENT_DATE NOT NULL,
        CMN_LAST_UPDT_DATE DATE DEFAULT CURRENT_DATE NOT NULL,
        CMN_ENTRY_USER_NO NUMBER(11),
        CMN_ENTRY_USER_TYPE NUMBER(1),
        CMN_LAST_UPDT_USER_NO NUMBER(11),
        CMN_LAST_UPDT_USER_TYPE NUMBER(1),
        CONSTRAINT SHT_USER_NTF_PK PRIMARY KEY (USER_NTF_ID)
    );

CREATE SEQUENCE SHT_USER_NTF_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER;