ALTER TABLE
    "SHT_USER_TALK_PURC" DROP COLUMN "SHT_USER_TALK_PURC_STATUS";
ALTER TABLE
    "SHT_USER_TALK_PURC" ADD (USER_TALK_PURC_BLOCK NUMBER(1) DEFAULT 0 NOT NULL);
ALTER TABLE
    "SHT_USER_TALK_PURC" ADD (USER_TALK_PURC_MUTE NUMBER(1) DEFAULT 0 NOT NULL);