CREATE TABLE "SHT_GROUP_PUBLISH" (
    GROUP_ID                  NUMBER(11)          NOT NULL,
    GROUP_NO                  VARCHAR2(11)        NOT NULL,
    GROUP_NAME                VARCHAR2(50)        NOT NULL,
    ADMIN_ID                  NUMBER(11)          NOT NULL,
    LEGAL_NUMBER              NUMBER(11)          DEFAULT 0 NOT NULL,

    CMN_DELETE_FLAG           NUMBER(1)           DEFAULT 0 NOT NULL,
    CMN_ENTRY_DATE            DATE                DEFAULT CURRENT_DATE NOT NULL,
    CMN_LAST_UPDT_DATE        DATE                DEFAULT CURRENT_DATE NOT NULL,
    CMN_ENTRY_USER_NO         NUMBER(11),
    CMN_ENTRY_USER_TYPE       NUMBER(1),
    CMN_LAST_UPDT_USER_NO     NUMBER(11),
    CMN_LAST_UPDT_USER_TYPE   NUMBER(1)
);

ALTER TABLE "SHT_GROUP_PUBLISH"
    ADD CONSTRAINT SHT_GROUP_PUBLISH_PK PRIMARY KEY (GROUP_ID);

CREATE SEQUENCE SHT_GROUP_PUBLISH_SEQ START WITH 1;