ALTER TABLE
    "SHT_USER_SETTING" ADD (PUSH_TALKROOM_FIRST_MSG NUMBER(1));

ALTER TABLE
    "SHT_USER_SETTING" ADD (PUSH_TALKROOM_TRANSACTION NUMBER(1));

ALTER TABLE
    "SHT_USER_SETTING" ADD (PUSH_FAVORITE NUMBER(1));

ALTER TABLE
    "SHT_USER_SETTING" ADD (MAIL_TALKROOM_FIRST_MSG NUMBER(1));
ALTER TABLE
    "SHT_USER_SETTING" ADD (MAIL_TALKROOM_TRANSACTION NUMBER(1));